import Header from "../../components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <section>
      <Header />
      {children}
    </section>
  );
}
