import { Provider } from "react-redux";
import Navbar from "../components/Navbar";
import { ReduxProvider } from "./features/todo/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import store from "./store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <ReduxProvider>
        <body className={inter.className}>
          {/* <Navbar /> */}
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
